# config.yaml - Configuration for the ML Pipeline

# --- Data Loading ---
data_loader:
  source_type: 'local' # options: 'local', 's3', 'gcs'
  input_path: 'data/raw/my_data.csv'
  # Optional cloud storage settings
  # bucket: 'my-ml-bucket'
  # input_key: 'raw_data/data.csv'

# --- Data Processing ---
data_transformer:
  # List of features to keep/use
  features:
    - 'feature1'
    - 'feature2'
    - 'feature3'
  target: 'target_variable'
  # Add other transformation params if needed, e.g., imputation strategy

data_splitter:
  test_size: 0.2
  random_state: 42 # for reproducibility

# --- Model Training ---
model_trainer:
  # Parameters specific to the chosen model (e.g., RandomForestClassifier)
  model_params:
    n_estimators: 100
    max_depth: 10
    random_state: 42 # separate random state for model algorithms

# --- Model Saving ---
model_saver:
  output_type: 'local' # options: 'local', 's3', 'gcs'
  output_path: 'models/trained_model.joblib'
  # Optional cloud storage settings
  # bucket: 'my-ml-bucket'
  # output_key_prefix: 'models/my_model/' # Can add versioning here later

# --- Evaluation ---
model_evaluator:
  metrics_path: 'results/metrics.json'

# --- General ---
pipeline_run_id: 'auto' # Can be set manually or generated